### ISSUE TITLE
Calendar page broken if using Resources 1.3

### ISSUE THREAD

**Issue by remocrevo** [ndlibersa/licensing#15]
The latest updates to the Resources module break the Licensing calendar page. The calendar is expecting the old Resource.subscriptionEndDate.  I’m not sure what the best solution is, but you probably just want the latest ResourcePayment.subscriptionEndDate?

Related to this is the idea of each license having some kind of expiration date, which was requested in issue #13

**Comment by doug-hahn** [comment]
This should be resolved.  The table column name is now dynamic and changes with the update to version 1.3 of the Resource module.
