### ISSUE TITLE
Provide consistency in footer

### ISSUE THREAD

**Issue by techsvcslib** [ndlibersa/licensing#25]
We need to use consistent footers throughout CORAL modules. Suggest using the same as was recently added to Resources as shown in the attached screenshot. Each module should have the following syntax:

Copyright statement. [Name of module] Module version [whatever the current version is]
CORAL Project Website | GitHub Site

![2015-10-19_10-49-22](https://cloud.githubusercontent.com/assets/3106487/10582858/850b2c14-764f-11e5-87eb-58255a87f3da.jpg)

**Comment by remocrevo** [comment]
@techsvcslib The same style footer has already been added to most modules, including this one. Modules that still need it are Reports and Management. I will open an issue for those modules.
